### ISSUE TITLE
Better Authentication Support

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [SpinlockLabs/github.dart#167]
We need the Add ability to know if username and password authentication was successful.

**Comment by robrbecker** [comment]
Thinking about this more. Credentials are included in each request and each request is stateless. The authorization is also dependent on the request you are making .. so if you specify a username and password, it may work to read from a public repo, but not write. Or it could work for a public repo, but not an organization.
I would recommend you do a permission check in your code that does an initial request to the repo that you will be working with. Then if you catch an `AccessForbidden` exception you'll know that your username and password doesn't work for that repo.
