### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<Map<String, dynamic>>' in type cast

### ISSUE THREAD

**Issue by AlexVincent525** [SpinlockLabs/github.dart#187]
Happened when running event poller.
https://github.com/SpinlockLabs/github.dart/blob/6d26e461965e830d0fb485c9358b18184e114231/lib/src/common/activity_service.dart#L348
Maybe change to `final json = List<Map<String, dynamic>>.from(jsonDecode(response.body));` ? This one works fine.

**Comment by robrbecker** [comment]
I tested your suggestion and it works for me. I'll push up the fix.

**Comment by robrbecker** [comment]
Fixed in https://github.com/SpinlockLabs/github.dart/commit/4aa3cf56b79ddfdfb49cbea0d0bba384e8aefa42
