### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [SpinlockLabs/github.dart#189]
I'd like to start working on rewriting this library to use github's new graphql api, but I'd need to get a way to get an access token first. Any idea on how to do this? I tried looking at docs, but the current methods I've seen launch a web browser, but that's rarely convenient. Can anyone help with this?

**Comment by robrbecker** [comment]
GraphQL is quite different. If you're thinking of doing this, I'd recommend 2 things
- have a graphql branch where you can freely push work to
- Leave the existing API in place and add an alternate entrypoint and subdir under lib/src for graphql code.
We've talked about it a little in the gitter chat. Feel free to jump in there to discuss approach https://gitter.im/SpinlockLabs/community

**Comment by robrbecker** [comment]
Try looking at https://pub.dev/packages/flutter_github_api I think they might have added extra oAuth stuff. Not sure though.

**Comment by ThinkDigitalSoftware** [comment]
Actually, After looking at this, unless the graphQl api had extra
functionality, I don't see the benefits yet
