### ISSUE TITLE
type 'List<dynamic>' is not a subtype of type 'List<Map<String, String>>'  in cast

### ISSUE THREAD

**Issue by timsneath** [SpinlockLabs/github.dart#196]
In line: 
https://github.com/SpinlockLabs/github.dart/blob/c28cb7cf3c298e7a9c642668829faad8d1c2b234/lib/src/common/github.dart#L390

I get an unhandled exception, processing this http response from GitHub: 
```
{"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}
```

**Comment by robrbecker** [comment]
Hi Tim! I'll get that fixed up tonight. Thanks for using the package!

**Comment by robrbecker** [comment]
I verified this issue .. can you try this branch to see if it works for you? https://github.com/SpinlockLabs/github.dart/tree/fix_bugs ?
