### ISSUE TITLE
Overencoding of query results in GitHub API failure

### ISSUE THREAD

**Issue by timsneath** [SpinlockLabs/github.dart#197]
Consider the following code:
```dart
  final search = SearchService(GitHub());
  final fixedQuery =
      'repo:flutter/flutter+is:open+is:issue+label:"a: annoyance"';
  final issueStream = search.issues(fixedQuery);
  int length = await issueStream.length;
  print(length);
```

This gives an error from GitHub, because the string is encoded to:
`?q=repo%3Aflutter%2Fflutter%2Bis%3Aopen%2Bis%3Aissue%2Blabel%3A%22a%3A%20annoyance%22`
instead of
`?q=repo%3Aflutter%2Fflutter+is%3Aopen+is%3Aissue+label%3A%22a%3A%20annoyance%22`

Note that the multiple query parameters are encoded into a single parameter (the `+` symbol is encoded as `%2B`). 

As a result, the URI becomes [this failing call](https://api.github.com/search/issues?q=repo%3Aflutter%2Fflutter%2Bis%3Aopen%2Bis%3Aissue%2Blabel%3A%22a%3A%20annoyance%22) instead of [this correct call](https://api.github.com/search/issues?q=repo%3Aflutter%2Fflutter+is%3Aopen+is%3Aissue+label%3A%22a%3A%20annoyance%22).

The culprit is:
https://github.com/SpinlockLabs/github.dart/blob/c28cb7cf3c298e7a9c642668829faad8d1c2b234/lib/src/util.dart#L16
which calls `Uri.encodeComponent()` on the entire string. 

If I understand the API correctly, the correct approach should be to call `Uri.encodeQueryComponent()` on each of the subsidiary query parameters, based on https://api.dart.dev/stable/2.7.0/dart-core/Uri/encodeQueryComponent.html.

**Comment by robrbecker** [comment]
It looks like your query is already encoded with + signs .. I think the query is supposed to be passed in as you would type it in github. For instance this code works for me (all I did was get rid of the + signs

```
final search = SearchService(GitHub());
    const fixedQuery =
      'repo:flutter/flutter is:open is:issue label:"a: annoyance"';
  final issueStream = search.issues(fixedQuery);
  int length = await issueStream.length;
  print(length);
```

**Comment by robrbecker** [comment]
If you continue to have problems, just re-open this issue.
