### ISSUE TITLE
(possible) issues w/ 6.0.4

### ISSUE THREAD

**Issue by pq** [SpinlockLabs/github.dart#199]
We've seen some failures since 6.04 that rolling back to 6.0.3 seems to address.

w/ 6.0.4:

https://travis-ci.org/dart-lang/linter/jobs/640064984?utm_medium=notification&utm_source=github_status

pinned to 6.0.3:

https://travis-ci.org/dart-lang/linter/jobs/640079167?utm_medium=notification&utm_source=github_status

**Comment by robrbecker** [comment]
Hey, thanks for reporting this. Looks like there's an unhandled null. 🤦‍♂ I'll get that fixed.

**Comment by robrbecker** [comment]
@pq Do you want to try this branch? https://github.com/SpinlockLabs/github.dart/pull/201

**Comment by pq** [comment]
Super!  Works locally. 

Trying on travis now: https://github.com/dart-lang/linter/pull/1980.

🤞

**Comment by pq** [comment]
LGTM!

https://travis-ci.org/dart-lang/linter/jobs/640138898?utm_medium=notification&utm_source=github_status

(API rate limit issues but those are expected.)

Thanks for the quick fix!
