### ISSUE TITLE
[question] how to do pagination control

### ISSUE THREAD

**Issue by pd4d10** [SpinlockLabs/github.dart#207]
Hi, just found this lib, really helpful!

I've noticed that all pagination related methods are returned as `Stream`. It is convenient if we want to get the full data of all pages, by piping it to the dest we specified.

The thing I have not figured out is how to do pagination control precisely. For example, if we want to do infinite loading in [a Flutter app](https://github.com/pd4d10/git-touch), we should not fetch the second page data until the screen is scrolled to the bottom.

It there any best practice for these cases? Thanks!

**Comment by robrbecker** [comment]
Thanks for your question. You are correct that the pagination is handled internally. It doesn't request the next pages until you try to get those values from the stream however. For instance, if you call `.toList()` on the stream it will get all the values and request all the pages of results. 

It's not a great solution, but you could handle the pagination in your flutter app, only reading the number of items that you need for the first page. If the user decides to go to the next page, read the next 10 from the stream and so on. Problems with this approach:
 - You'd need to store all the previous page values in a list somewhere, thus using memory.
 - You can only start the stream from the first page, so if you wanted to start at page 10, you'd have to load all the results up to page ten, even though you'd only use/display page 10.

This could work but I feel it's a bit clumsy and not always the most efficient in terms of network and memory usage if you want to virtualize a large list of items. Your question made me look at the API  closely to see how it would be possible to give more direct control over pagination. One approach might be to add page and per_page optional params to all the listXXX methods. It's a non-breaking change but it still wouldn't give you the total number of pages/results, so couldn't create a UI with only the right number of pages as options.

Th other option might be to add additional methods along side of the list methods  that do give control over pagination and only return pages of results at a time and full information of the number of results. Something more similar to how code search works. See
https://github.com/SpinlockLabs/github.dart/blob/master/lib/src/common/search_service.dart#L66 and https://github.com/SpinlockLabs/github.dart/blob/master/lib/src/common/model/search.dart#L13

Do you have any preference? What items are you trying to paginate?

**Comment by pd4d10** [comment]
Thanks for the quick reply! Clear enough.

Temporarily I'm using the common method `getJSON`: [code here](https://github.com/pd4d10/git-touch/blob/048adebb74008d108edbafc719247014395f903c/lib/screens/gh_org_repos.dart#L22-L25). It seems works fine! 🎉

I'm not sure if other developers have the same problems. If so perhaps we could implement a common pattern to pass `page` and `per_pages` params in.

I'm going to close this issue since the problem is solved. Thanks!
