### ISSUE TITLE
Remove `null` fields on `json.encode`

### ISSUE THREAD

**Issue by pd4d10** [SpinlockLabs/github.dart#211]
It seems the `null` fields would cause some issues. Take create issue API as an example:

```dart
import 'package:github/github.dart';

main(List<String> args) async {
  final client = GitHub(auth: Authentication.withToken('xxx-token')); // Replace with a valid token
  final res = await client.issues.create(
    RepositorySlug('flutter', 'flutter'), // Replace with a test repo
    IssueRequest(
      title: 'title',
      body: 'body',
    ),
  );
}
```

throws an error as follows:

> Unhandled Exception: GitHub Error: {"message":"Invalid request.\n\nFor 'properties/labels', nil is not an array.","documentation_url":"https://developer.github.com/v3/issues/#create-an-issue"}

It is because of the `null` fields are not removed on encoding:

```json
{
  "title": "title",
  "body": "body",
  "labels": null,
  "assignee": null,
  "state": null,
  "milestone": null
}
```

**Comment by pd4d10** [comment]
I could submit a PR to fix it by tweaking `json_serializable` config, but not sure if there are other side effects.

**Comment by robrbecker** [comment]
Hmm that's not great. Taking a look.
