### ISSUE TITLE
cloneUrls field is null

### ISSUE THREAD

**Issue by glesica** [SpinlockLabs/github.dart#214]
Yo dawg, I'm getting a bunch of repos, but then their `cloneUrls` field is `null`...

```dart
final github = GitHub(
  auth: Authentication.withToken('...'),
);
await github.repositories.listUserRepositories('glesica').first.then((r) => r.cloneUrls.ssh);
```

This will throw an exception:

```
Unhandled exception:
NoSuchMethodError: The getter 'ssh' was called on null.
Receiver: null
Tried calling: ssh
...
```

Edit: To be clear, I can construct it easily enough, just seems like the field should either exist or not.

**Comment by robrbecker** [comment]
@glesica 
It appears that the API has changed at some point. The repository response has the clone urls at the top level instead of a nested object. I put up https://github.com/SpinlockLabs/github.dart/pull/217 if you'd like to test if it works for you.
