### ISSUE TITLE
Re-export PullRequestEvent?

### ISSUE THREAD

**Issue by digiter** [SpinlockLabs/github.dart#220]
This package no longer exports [PullRequestEvent](https://github.com/SpinlockLabs/github.dart/blob/e578e1f3a8135895fd649f8382692403e9e548f1/lib/src/server/hooks.dart#L161) since version 6.0. Our code base depends on the `action` field. Is there any plan to re-export it?

**Comment by robrbecker** [comment]
Hi @digiter! PullRequestEvent and other events are actually exported, but 
 - Are not exported for web .. only for `dart.io` aka server, command line or Flutter
 - Don't seem to show up in the API docs that are generated :(

This is a consequence of automatically "working" cross platform. There's a conditional import that looks like it breaks docs generation and possibly IDE autocomplete. 

Give it a try to use the class and see if it actually works. I'll see if I can get the docs generating right.

**Comment by digiter** [comment]
Thanks for the reply! I have tried using PullRequestEvent with ignores and it does work. BTW we are using it in a server.

**Comment by robrbecker** [comment]
I'll leave this issue open for now to track the progress of updating documentation generation to include things that aren't included.

**Comment by robrbecker** [comment]
I looked into how to get dartdoc to handle the conditional import/exports better but it didn't work. So an easier solution was to add a new top level entry point named hooks.dart that causes dartdoc to document those clases. When writing a hooks server or CLI you can add the new import to have your IDE autocomplete and "know about" these classes.
See https://pub.dev/documentation/github/latest/hooks/hooks-library.html

Closing this issue now. Thanks for your help in identifying this problem.
