### ISSUE TITLE
Migrate to NNBD

### ISSUE THREAD

**Issue by pq** [SpinlockLabs/github.dart#236]
As the ecosystem moves towards embracing null-safety, it'd be great to get this package migrated.

See: https://dart.dev/null-safety

Happy to help if you hit any snags!

**Comment by robrbecker** [comment]
I agree! I gave it a once over a couple weeks ago but there were still dependencies that needed to upgrade first. I'll be sure to get it updated as soon as I can. Thanks for reaching out!

**Comment by robrbecker** [comment]
Looks like it's close to being unblocked. Just waiting on http
![image](https://user-images.githubusercontent.com/314858/101971414-66547b80-3bee-11eb-9f89-dfdf420086bc.png)

**Comment by pq** [comment]
I know folks are actively looking at `http`.  Maybe @natebosch?

I see a tracking issue here: https://github.com/dart-lang/http/issues/501

Thanks a million for taking a look @robrbecker!

**Comment by robrbecker** [comment]
The http package has a null safe release now. I'll take another shot at converting this package this week.

**Comment by pq** [comment]
Awesome.  Thanks!

**Comment by robrbecker** [comment]
I put up an initial draft PR here https://github.com/SpinlockLabs/github.dart/pull/244
@pq would you be up for giving it a once over?

**Comment by pq** [comment]
sorry for the slow reply!  fighting a few fires here but will happily take a look in the next few days.  thanks for pushing on this!

**Comment by pq** [comment]
Thanks so much for pushing on this! I've done some integrating and while I haven't dug deeply there are some spots where we're getting nullable results and ideally they'd be non-null.  For example, it would be fantastic if `Issue` could guarantee a non-null `url`, `title`, etc.  Not sure about implications.

**Comment by bsutton** [comment]
At some point can we get a version released without the -nullsafety. Google is calling for package maintainers to publish a 'pre-release' version such as 7.1.0.
Usage of the nullsaftey designation results in warnings when a dependant package attempts to publish a pre-release.

**Comment by robrbecker** [comment]
Closing this issue. Null safe versions are 8+
