### ISSUE TITLE
Library Demos hang

### ISSUE THREAD

**Issue by Hixie** [SpinlockLabs/github.dart#242]
https://github.directcode.org/demos/ never loads for me. There's a sync XHR that never returns.

**Comment by robrbecker** [comment]
I believe that domain has been retired and now the demos are broken. I think a good solution would be to publish the demos to github pages.

**Comment by robrbecker** [comment]
I've moved the demos to be hosted on github pages and updated the link in the readme. Use http://spinlocklabs.github.io/github.dart/ (you'll probably need to provide a github token for them to work)
