### ISSUE TITLE
Request for review information on PullRequest

### ISSUE THREAD

**Issue by Piinks** [SpinlockLabs/github.dart#267]
I am implementing a bot that manages PR in flutter/flutter and I would like to be able to access `requested_reviewers` and the number of `review_comments` for a given PR.

For example:

https://api.github.com/repos/flutter/flutter/pulls/90295

has two `requested_reviewers`, goderbauer and hansmuller. And it has 0 `review_comments`.

**Comment by Piinks** [comment]
Proposed in https://github.com/SpinlockLabs/github.dart/pull/268

**Comment by robrbecker** [comment]
Hi Kate! I'd love to help get this added. I'll take a look at the pr.
