### ISSUE TITLE
[Proposal] Hope to standardize the code

### ISSUE THREAD

**Issue by ggdream** [SpinlockLabs/github.dart#273]
Hello, the offical team.

I am glad that there is such a third-party library in Dart, which is very convenient to help us improve development efficiency.
I am using this library for a small project these days, and it is not good in the process of using it.

First of all, let's see the entry `GitHub(auth: xxx)`. I have to admit that in some other languages (such as `Golang`), this package is particularly good, but in Dart, it is a bit bad. 
- Account and password authentication methods have been banned by GitHub, so this category should be set to `@Deprecated`.
- From the perspective of Dart syntax, it may be better to use `selected args` and `assert` in this situation.

Second, in many places, Dart syntax is not used properly, and many of the parameters that should be set for `required` are `selected`, which is directly asserted by `!` in the source code and made a judgment. E.g:
https://github.com/SpinlockLabs/github.dart/blob/c72b46031fcd326820cbc5bb0c3b4b1c15e075e4/lib/src/common/repos_service.dart#L160-L178
https://github.com/SpinlockLabs/github.dart/blob/c72b46031fcd326820cbc5bb0c3b4b1c15e075e4/lib/src/common/model/repos_contents.dart#L114-L122
To be honest, the code is a bit bad. I haven't used `GitHub API` many times before, so I tried this library first, but because of the code listed above, I couldn't troubleshoot the error. Because if I don't look at the source code, I have no way to know whether you have set default parameters for the original mandatory parameters.

Therefore, I solved the problem by reading the GitHub document and analyzing the network requests issued by DevTools-Network. Speaking of documentation, `example` may also need to be modified. No matter for `native` or `flutter`, the content of dart-web is not needed. It seems to be too strenuous.

Hope to get better and better.

**Comment by robrbecker** [comment]
Closing and linked separate issues for the 3 items that came out of this discussion:

remove username/password: https://github.com/SpinlockLabs/github.dart/issues/280
flutter example: https://github.com/SpinlockLabs/github.dart/issues/219
editRepository dartdocs: https://github.com/SpinlockLabs/github.dart/issues/282

**Comment by ggdream** [comment]
Good work



| |
gdream
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Rob ***@***.***> |
| 日期 | 2021年11月28日 23:08 |
| 收件人 | ***@***.***> |
| 抄送至 | Dorain ***@***.******@***.***> |
| 主题 | Re: [SpinlockLabs/github.dart] [Proposal] Hope to standardize the code (Issue #273) |

Closing and linked separate issues for the 3 items that came out of this discussion:

remove username/password: #280
flutter example: #219
editRepository dartdocs: #282

**Comment by theRealBitcoinClub** [comment]
@ggdream Would you be able to give any advice on my latest comment in: https://github.com/SpinlockLabs/github.dart/issues/219 ?
