### ISSUE TITLE
Add publish package github action

### ISSUE THREAD

**Issue by CaseyHillers** [SpinlockLabs/github.dart#278]
https://github.com/marketplace/actions/publish-dart-flutter-package

This will enable the plugin to be auto-published when commits land.

**Comment by CaseyHillers** [comment]
@robrbecker do you mind taking a look? It requires adding the secret for the pub info in the admin settings for this repo.

**Comment by robrbecker** [comment]
@CaseyHillers I will take a look tonight

**Comment by robrbecker** [comment]
added the repository secret named `CREDENTIAL_JSON`

**Comment by robrbecker** [comment]
Ok so it's working! When a release is created in github the workflow will publish it to pub.dev!

Next up 
- auto-bump the version (maybe something like cider https://pub.dev/packages/cider)
- Have github autogenerate the release notes
- Update the changelog with those release notes and commit them
- Then create the release in github

**Comment by CaseyHillers** [comment]
Thank you so much! This is great
