### ISSUE TITLE
Add post-submit publish step

### ISSUE THREAD

**Issue by CaseyHillers** [SpinlockLabs/github.dart#299]
Currently, the actions are configured to run --dry-run to verify everything. It would be nice if we could let automation publish it as well.

This would prevent random requests like https://github.com/SpinlockLabs/github.dart/pull/298

**Comment by CaseyHillers** [comment]
\cc @robbecker-wf any thoughts on this? We've done this in https://github.com/flutter/plugins and could re-use the publishing logic here (we just need to get a service account generated and added to the admin settings for the project)

**Comment by robrbecker** [comment]
I'd love to release and publish after each PR merge! We'd just need to make sure that
- The changelog is automatically updated and committed
- The version is correct in the pubspec and is the correct semver bump
- The release is created in github

I recently started playing around with a github action & script to do all that but will take a look at what you've done already.

**Comment by robrbecker** [comment]
FWIW this repo will already automatically publish to pub when a release is created in github (See https://github.com/SpinlockLabs/github.dart/blob/master/.github/workflows/publish_release.yml)

What I'm working on is a script to do what my previous post says (create the release correctly).

**Comment by robrbecker** [comment]
@CaseyHillers @kevmoo Ok, I've set up automatic release and publish every merge. This is the first release to automatically do it https://github.com/SpinlockLabs/github.dart/releases/tag/9.0.3

I'll also update the readme and contributing guide so people know how to work with the "bot".
Basically, no need to ever manually edit the version in the pubspec. Just add the correct semver label on your PR (one is required) and that segment will be bumped on merge.
The changelog is updated and release notes are autogenerated. If we do a major, it's possible to go back and add in the breaking changes description to both the changelog and release notes.

**Comment by CaseyHillers** [comment]
Thank you!

Any blockers with uploading pub credentials so the release script can run `pub publish` as well?

**Comment by robrbecker** [comment]
I already had auto-publish working when a github release is created. So, no problem there.

**Comment by robrbecker** [comment]
https://github.com/SpinlockLabs/github.dart/blob/master/CONTRIBUTING.md#releasing--publishing
