### ISSUE TITLE
Switch merge method to only allow squash

### ISSUE THREAD

**Issue by CaseyHillers** [SpinlockLabs/github.dart#321]
Currently we allow all 3 options for merges (merge commit, squash and merge, and rebase).

![image](https://user-images.githubusercontent.com/2148558/177867488-de1cad04-edf3-440c-8258-a4dbef79cbba.png)

This makes it somewhat difficult to automate releases and the CI systems. If we could assume every PR is merged into a single commit:
  - We can easily run releases on merged PRs
  - Running CI on every commit merged doesn't make sense, as we only expect the latest to pass
  - Clearer history/changelog (one entry per PR)

An alternative I can see is that we update all the GitHub actions to be done on merged PRs, but I think this becomes something we have to remember for maintenance purposes.

@robbecker-wf @kevmoo any thoughts here?

**Comment by robbecker-wf** [comment]
I'm ok with squash and merge as the only choice.

**Comment by robbecker-wf** [comment]
It is done.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/6053699/177872283-66d2edd8-252d-4773-9966-ac715be8a52e.png">
