### ISSUE TITLE
Timeline events

### ISSUE THREAD

**Issue by Hixie** [SpinlockLabs/github.dart#364]
I would like to make use of this API: https://docs.github.com/en/rest/issues/timeline

If I were to implement support for this and submit a PR, is this something that would be considered? (I'm happy to look into adding support, but I'd rather not start if it won't be used 😅.)

**Comment by robrbecker** [comment]
That would be a great addition!

**Comment by Hixie** [comment]
Cool, I'll see what I can do.

**Comment by Hixie** [comment]
@robrbecker Couple of questions.

- Some of the Timeline APIs sometimes return a Team. The package already has a `Team` class, but it has a different (overlapping) set of properties. Should I augment `Team` with the properties that this API might return when it returns a team, or should I have two different classes for the different contexts?

- I've been using the response schema found on https://docs.github.com/en/rest/issues/timeline?apiVersion=2022-11-28 to autogenerate the model classes as a starting point (I'll include the script that does it in case it helps for the future), but I find that this documentation contradicts some of the other GitHub docs, e.g. the prose on https://docs.github.com/en/webhooks-and-events/events/issue-event-types . Do you have any experience with such problems or any suggestions on dealing with it? Obviously at the end of the day I'll try to test these endpoints with real data and make it consistent with reality that way, but there's a good chance I won't be able to test every single part of the API with real data.

**Comment by Hixie** [comment]
- I notice none of the models have the `url` property which seems to be a self-reference for the REST API call itself. Is that intentional? Are there other properties that I should be explicitly not including?

**Comment by robrbecker** [comment]
fixed in https://github.com/SpinlockLabs/github.dart/pull/366

**Comment by robrbecker** [comment]
released in https://github.com/SpinlockLabs/github.dart/releases/tag/9.12.0
